#!/usr/bin/env python3
"""Writes src/granular_tables.inc: the Hann window, Grain Size and
Density tables the granular mode reads. Rerun after changing any curve."""
import math, os

out = os.path.join(os.path.dirname(os.path.abspath(__file__)), '..',
                   'src', 'granular_tables.inc')
# The first line is blank: GNU as can misread an included file's first line
# when the .include falls at the wrong spot in the including file's input
# buffer ("junk at end of line"), and a blank line makes that harmless.
L = ["",
     "| granular_tables.inc - generated by tools/gen_granular_tables.py. Do not edit.",
     "    .align 4",
     "| Hann window, 256 steps, Q15: 32767 * sin^2(pi*(i+0.5)/256)",
     "hann_tab:"]
h = [round(32767 * math.sin(math.pi * (i + 0.5) / 256) ** 2) for i in range(256)]
L += ["    .word " + ",".join(map(str, h[i:i + 16])) for i in range(0, 256, 16)]
L += ["| Grain Size: dial 0..127 -> 480 * 100^(d/127) output samples, 10 ms .. 1 s",
      "gsize_tab:"]
s = [round(480 * 100 ** (d / 127)) for d in range(128)]
L += ["    .long " + ",".join(map(str, s[i:i + 8])) for i in range(0, 128, 8)]
L += ["| Density: dial 0..127 -> grain spacing as a multiple of grain length, Q8:",
      "| 256 * 2^(2 - 4d/127) - four lengths apart (gaps) .. a quarter (4 overlapping)",
      "gdens_tab:"]
g = [round(256 * 2 ** (2 - 4 * d / 127)) for d in range(128)]
L += ["    .word " + ",".join(map(str, g[i:i + 16])) for i in range(0, 128, 16)]
L += ["| Stretch Speed: dial 0 = frozen, else 2^((d-96)/16) in Q16 - 96 is the",
      "| original speed, 1 is about 1/60, 127 about 3.8x",
      "    .align 4",
      "gspeed_tab:"]
v = [0] + [round(65536 * 2 ** ((d - 96) / 16)) for d in range(1, 128)]
L += ["    .long " + ",".join(map(str, v[i:i + 8])) for i in range(0, 128, 8)]
L += ["    .align 4",
      "| ---- Pluck (Karplus-Strong) ----",
      "| Strike length: dial 0..127 -> 48 * 1000^(d/127) samples, 1 ms .. 1 s",
      "pexc_tab:"]
e = [round(48 * 1000 ** (d / 127)) for d in range(128)]
L += ["    .long " + ",".join(map(str, e[i:i + 8])) for i in range(0, 128, 8)]
# Tone: the loop's one-pole lowpass coefficient, Q10, 0.08 (dark) .. 1.0 (open)
a = [round(1024 * 12.5 ** ((d - 127) / 127)) for d in range(128)]
L += ["| Tone: loop lowpass coefficient a, Q10: 1024 * 12.5^((d-127)/127), 0.08 .. 1",
      "pdamp_tab:"]
L += ["    .word " + ",".join(map(str, a[i:i + 16])) for i in range(0, 128, 16)]
L += ["| ...and the delay that lowpass adds at low frequencies, (1-a)/a samples in",
      "| Q8, taken off the loop length so a dark string stays in tune",
      "pcomp_tab:"]
c = [round(256 * (1024 - x) / x) for x in a]
L += ["    .word " + ",".join(map(str, c[i:i + 16])) for i in range(0, 128, 16)]
L += ["| Feedback: loop gain g, Q15: 32768 * (1 - 0.1 * 2^(-10d/127)), 0.9 .. 0.9999",
      "pfb_tab:"]
g = [min(32767, round(32768 * (1 - 0.1 * 2 ** (-10 * d / 127)))) for d in range(128)]
L += ["    .word " + ",".join(map(str, g[i:i + 16])) for i in range(0, 128, 16)]
L += ["| ---- Wavetable ----",
      "| Detune: each side voice's pitch offset as a Q16 ratio - 1, for",
      "| 50 * (d/127)^2 cents: finer near zero, +-50 cents at the top",
      "wdet_tab:"]
w = [round(65536 * (2 ** ((50 * (d / 127) ** 2) / 1200) - 1)) for d in range(128)]
L += ["    .word " + ",".join(map(str, w[i:i + 16])) for i in range(0, 128, 16)]
L += ["| ---- Lo-fi ----",
      "| Rate: sample-and-hold step through the 2x (96 kHz) buffer, Q16:",
      "| 32768 * 2^(-(127-d)*5.585/127) - dial 127 holds each 48 kHz sample (no",
      "| change), 0 takes a new one about 1,000 times a second",
      "lrate_tab:"]
r = [round(32768 * 2 ** (-(127 - d) * 5.585 / 127)) for d in range(128)]
L += ["    .word " + ",".join(map(str, r[i:i + 16])) for i in range(0, 128, 16)]
L += ["| Crush: bits kept = 16 - round(15d/127); the mask keeps that many bits of",
      "| a sample in the buffer's <<15 format - dial 0 is 16 bits (clean), 127 is 1",
      "    .align 4",
      "lcrush_tab:"]
m = []
for d in range(128):
    b = 16 - round(15 * d / 127)
    m.append((-(1 << (31 - b))) & 0xffffffff)
L += ["    .long " + ",".join('0x%08x' % x for x in m[i:i + 8]) for i in range(0, 128, 8)]
L += ["| Tape / Vinyl Tone: one-pole lowpass coefficient in the 96 kHz buffer, Q16:",
      "| 65535 * 2^(-(127-d) * 5.06/127) - 127 passes everything, 0 is a = 0.03,",
      "| about 460 Hz",
      "    .align 4",
      "tvtone_tab:"]
v = [min(65535, round(65536 * 2 ** (-(127 - d) * 5.06 / 127))) for d in range(128)]
L += ["    .word " + ",".join(map(str, v[i:i + 16])) for i in range(0, 128, 16)]
# Grain shapes beside hann_tab, 256 steps each, Q15
tri = [round(32767 * (1 - abs((i + 0.5) / 128 - 1))) for i in range(256)]
perc = []
for i in range(256):
    if i < 12:
        perc.append(round(32767 * (i + 0.5) / 12))           # fast attack
    else:
        perc.append(round(32767 * math.exp(-4.6 * (i - 12) / 243)))  # to about -40 dB
sq = [round(32767 * min(1, (i + 0.5) / 8, (255.5 - i) / 8)) for i in range(256)]
for name, tab, what in (("tri_tab", tri, "Triangle"), ("perc_tab", perc, "Perc: 12-step attack, exponential decay to ~-40 dB"),
                        ("sq_tab", sq, "Square: flat, with 8-step ramps so grain edges do not click")):
    L += ["| Grain shape: " + what, "    .align 4", name + ":"]
    L += ["    .word " + ",".join(map(str, tab[i:i + 16])) for i in range(0, 256, 16)]
L += ["    .align 4"]
open(out, 'w').write("\n".join(L) + "\n")
